### ISSUE TITLE
Setup Delibot

### ISSUE THREAD

**Issue by acocalypso** [Widdin/DeliBot#22]
I tried to Setup DeliBot but the config.ini will not load.
Here it complains about the Setting section

Part of config.ini

```
[SETTINGS]
prefix: !
```

```
Traceback (most recent call last):
  File "delibot/bot.py", line 34, in <module>
    bot = commands.Bot(command_prefix=config['SETTINGS']['prefix'], intents=intents)
  File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'SETTINGS
```

**Comment by acocalypso** [comment]
Im using Ubuntu 20 and tried it python3 venv

**Comment by acocalypso** [comment]
After the added from you I could see that the config file wasn't loaded the way I was starting the bot.py

Now the config is found but now its not able to load the cogs modules:

```
/DeliBot/delibot$ ../deli_env/bin/python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 46, in <module>
    bot.load_extension(extension)
  File "/home/aco/DeliBot/deli_env/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 662, in load_extension
    raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension 'cogs.owner' could not be loaded.

```

**Comment by acocalypso** [comment]
@Widdin so you have any Idea why the cogs modules can't be found? I get the message with and without venv.

**Comment by Widdin** [comment]
> @Widdin do you have any Idea why the cogs modules can't be found? I get the message with and without venv.

I just tried on `Ubuntu 18.04.5` and it worked fine for me.
What did you do in order to solve the config issue? Could be the same with the cogs, if they arent' found.

**Comment by acocalypso** [comment]
I deleted the local repo and did a new git clone and now its working.
