### ISSUE TITLE
Embed message not updating anymore after pinning post ?

### ISSUE THREAD

**Issue by equinoxe3d** [Widdin/DeliBot#3]
We have created a raid message for an upcoming EX raid, and while it worked perfectly at first now the post stopped updating itself with the reactions (even after waiting one hour for the refresh). Our best guess is that it somehow broke after our admin pinned the post.

In the screenshot below, we have one Valor and two Mystic players not showing up on the post, despite having the correct number in their respective team reaction :

![image](https://user-images.githubusercontent.com/38863025/39437758-c9c763f6-4c6f-11e8-830f-2d31c5df5ec8.png)

Is it something that can be reproduced on your side, or should we simply avoid pinning Delibot posts ?

**Comment by fraqqer** [comment]
I'm having the same issue too, specifically EX raids are not updating for me.

![exraidnotupdating](https://user-images.githubusercontent.com/29012130/39958805-cff03840-55ff-11e8-8a43-57eb7111e80b.png)

However, normal raids seem to be working just fine for me.

![exraidnotupdating](https://user-images.githubusercontent.com/29012130/39958810-f1bd471a-55ff-11e8-86d2-13570f4ccc48.png)

**Comment by DrategoniZero** [comment]
We're having the same issue with our server, but the messages aren't pinned.

![reaction bug](https://user-images.githubusercontent.com/42421380/44174307-a5379c80-a0da-11e8-828d-43d4cbf05afd.png)

Regular raids also seem unaffected.

![regular raid](https://user-images.githubusercontent.com/42421380/44174255-79b4b200-a0da-11e8-8068-aa1695642ed8.png)

Location has been edited out for confidentiality purposes, it was set correctly for each example.

**Comment by OfficialWiddin** [comment]
I'm working on a version that will hopefully and most likely work better! Thank you for the patience
